### ISSUE TITLE
link to boilerplate_function.py not working

### ISSUE THREAD

**Issue by nniens** [Amsterdam/data-processing#10]
On https://amsterdam.github.io/data-processing/introduction.html#add-function is refered to the script boilerplate_function.py The path (https://github.com/Amsterdam/data-processing/blob/master/src/boilerplate_function.py) is not working and should be https://github.com/Amsterdam/data-processing/blob/master/src/datapunt_processing/boilerplate_function.py instead.

**Comment by Lytrix** [comment]
Thanks for catching that broken link! It's been updated.
