### ISSUE TITLE
per functie beschrijving en args/returns toevoegen

### ISSUE THREAD

**Issue by JLK1990** [Amsterdam/data-processing#3]
Wanneer alle functies beschreven worden en wordt beschreven wat de input en output is, maakt dit het makkelijker voor de gebruiker om te beoordelen of dit voor hem/haar een handige functie is.

**Comment by Lytrix** [comment]
I've moved the table of contents to the main page of our readthedocs to see the overview of the modules and functions. Each function is described here what it does: 
https://amsterdam.github.io/data-processing/

Please let us know if something is unclear in the description.
