### ISSUE TITLE
nieuwe functie: plotten op kaart Amsterdam

### ISSUE THREAD

**Issue by JLK1990** [Amsterdam/data-processing#4]
Voor de map /data_visualization
Om het makkelijk te maken om aan de hand van stadsdelen/buurten/wijken en een getal/percentage een plot te maken. 
input is dataframe met: 
- stadsdelen, buurten of wijken (hangt ervanaf op wat voor niveau je de plot wilt)
- getal of percentage per niveau
output:
- kaart van  Amsterdam met getal of percentage per niveau geplot

Vanwege de plot in python notebook (.ipynb)

**Comment by Lytrix** [comment]
Thanks for the new Jupyter notebook example you added yourself!
https://github.com/Amsterdam/data-processing/blob/master/src/data_visualization/GeoJSON_and_choropleth-Amsterdam.ipynb
